worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       ./conf/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    # Gzip settings
    gzip  on;
    gzip_disable "msie6";

    server {
        listen 8080;
        server_name localhost;

        location /api1 {
            rewrite ^/api1(/.*)$ $1 break;
            proxy_pass http://192.168.200.130:8000; # 替换为你的 API 服务地址
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api2 {
            rewrite ^/api2(/.*)$ $1 break;
            proxy_pass http://192.168.200.130:8001; # 替换为你的 AI API 服务地址
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 托管静态资源：所有非 API 请求都指向 dist 目录
        location / {
            root ./dist;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}